brief: We will uses the programming language [python](https://www.python.org) to study common tasks in discrete mathematics applications in computer science. So we will start with a small exercise to help you get become familiar with python syntex.
type: page
state: public
note: "https://hourofcode.com/toxicodecompute2"