brief: A short presentation on the module - aims, proposed content, contact hours and assessment structure. These slides document describes how the Autumn 2020 version of the module, as specified in the official module descriptor, will be realised.
type: beamer
outline: 
 - Aim and motivation for this module
 - Administration trivia --- Contact hours, Assessment structure, \ldots
 - Tools and resources